

export const datas = [
    {
        id : 1,
        avator : "Ben Ford",
        username : "Ben Ford",
        price : 80000,
        discount_price : 3050,
        name : "Blue View Home",
        address : "2854 Meadow View Drive, Hartford, USA",
        backgroundImg : "assets/imgs/gallery/work-1.jpg.webp",
    },
    {
        id : 2,
        avator : "Ben Ford",
        username : "Ben Ford",
        price : 50000,
        discount_price : 3050,
        name : "Blue View Home",
        address : "2854 Meadow View Drive, Hartford, USA",
        backgroundImg : "assets/imgs/gallery/work-2.jpg.webp",
    },
    {
        id : 3,
        avator : "Ben Ford",
        username : "Ben Ford",
        price : 60000,
        discount_price : 3050,
        name : "Blue View Home",
        address : "2854 Meadow View Drive, Hartford, USA",
        backgroundImg : "assets/imgs/gallery/work-3.jpg.webp",
    },
    {
        id : 4,
        avator : "Ben Ford",
        username : "Ben Ford",
        price : 90000,
        discount_price : 3050,
        name : "Blue View Home",
        address : "2854 Meadow View Drive, Hartford, USA",
        backgroundImg : "assets/imgs/gallery/work-4.jpg.webp",
    },
    {
        id : 5,
        avator : "Ben Ford",
        username : "Ben Ford",
        price : 50000,
        discount_price : 3050,
        name : "Blue View Home",
        address : "2854 Meadow View Drive, Hartford, USA",
        backgroundImg : "assets/imgs/gallery/work-5.jpg.webp",
    },
    {
        id : 6,
        avator : "Ben Ford",
        username : "Ben Ford",
        price : 80000,
        discount_price : 3050,
        name : "Blue View Home",
        address : "2854 Meadow View Drive, Hartford, USA",
        backgroundImg : "assets/imgs/gallery/work-6.jpg.webp",
    },
]